### ISSUE TITLE
AttributeError will be raised if User is not using email.

### ISSUE THREAD

**Issue by moonwalkerpoday** [chrisclark/django-sql-explorer#551]
I am using a custom user that inherits from AbstractBaseUser and I get an AttributeError.

<img width="376" alt="image" src="https://github.com/groveco/django-sql-explorer/assets/25785388/4757259f-edfd-4d6f-b2a9-140942f852b7">

The reason is that the email is referenced in the created_by_user_email method of the QueryForm.

```
...
    @property
    def created_by_user_email(self):
        return self.instance.created_by_user.email if \
            self.instance.created_by_user else '--'
...
```

I think it is better not to fix it to email, because there are cases where email is not used.
I will create a pull request, any other ideas or opinions?
thank you

**Comment by moonwalkerpoday** [comment]
Sorry, the issue was duplicated.
https://github.com/groveco/django-sql-explorer/issues/422

**Comment by marksweb** [comment]
No change was made following #422 from what I can see.

You could raise a PR that addresses this, but it's a bigger problem than just `created_by_user_email`.

In a potential change, `created_by_user_email` should be renamed because what this is actually doing is providing a way to identify which user is associated to something in the templates. But obviously `created_by_user_id` or something would make you expect a number for the user's ID, when infact what we're looking for here is an identifier for a user.

There is more functionality in the app that expects a user to have an email address, so that would need to be fixed as well if we're going to bring support for users without an email address.

**Comment by chrisclark** [comment]
Addressed via: https://github.com/chrisclark/django-sql-explorer/pull/606
