### ISSUE TITLE
Possibility to make DDL/DML bypassing Restrictions in EXPLORER_SQL_BLACKLIST

### ISSUE THREAD

**Issue by okunev-e** [chrisclark/django-sql-explorer#554]
Hi!

There exists the Possibility to make DDL/DML Queries bypassing the Restrictions in EXPLORER_SQL_BLACKLIST.

Founded at django-sql-explorer ver.3.2 and PostgreSQL ver.15.2 (and 14.x).

PostgreSQL includes its own programming language named PL/pgSQL.
Using it I can perform any of DDL/DML Queries bypassing EXPLORER_SQL_BLACKLIST.
The Example is below:
```SQL
DO $$
DECLARE
BEGIN
  -- Write here your SQL DDL/DML (insert/update/delete/alter etc.)
  update public.<table_name>
  set  <field> = <new_value>
  where <search_conditions>;
END;
$$ LANGUAGE plpgsql;
```

My Question is: is it well known behavior or a bag or i just need extend EXPLORER SQL BLACKLIST with "do"?

In my Opinion, we need common Solution to restrict Processing PL-Scripts for other DataBases and their own PL Syntax (for example, Oralce with PL/SQL). If it can be made, of course.

**Comment by chrisclark** [comment]
I don't quite understand this -- wouldn't the Blacklist still block this because the word 'update' appears in the string? Wrapping it in the DO $$ doesn't sidestep that fact, right?

Also - the blacklist is really not designed to be bulletproof; the intent is really to allow small projects and teams to avoid shooting themselves in the foot by accidentally executing something they didn't intend to. I suspect there are a significant number of ways to bypass it in an adversarial context.

The real solution is, as recommended in the docs, to connect via a readonly database connection.

I'm going to close this issue as a result - though of course appreciate you taking the time to write it!
