### ISSUE TITLE
Disable merge commits on PRs

### ISSUE THREAD

**Issue by marksweb** [chrisclark/django-sql-explorer#574]
Just looking at the commits on master, I thought I'd just mention that setting PRs to merge with a squash keeps the commits to master tidy and, if it's not stating the obvious, ensures that a PR merges as just 1 commit rather than all the commits the author made to the PR. This is how I usually setup a repo;

<img width="813" alt="Screenshot 2024-01-20 at 01 18 02" src="https://github.com/chrisclark/django-sql-explorer/assets/1461191/1623e623-062c-4f54-8b1d-f85f28c28162">

I've also setup a branch for supporting 3.x as I foresee the current changes in master making the next release 4.0. So it would be good to add branch protection to it;
https://github.com/chrisclark/django-sql-explorer/tree/support/3.x

**Comment by chrisclark** [comment]
Thanks Mark. And sorry for being a less-sophisticated maintainer than you :)

I do not love the 'always squash' -- because you lose a lot of context on changes. In the large front-end refactor I made, for instance, I think the git blame is much more useful as a result of having a ~dozen different commits explaining how things got there. One giant commit with all of the changes in one shot doesn't have much context. I'm totally open to being convinced otherwise though! What do you think of that argument? I did go and interactively rebase a bunch of the commits to make it more linear and cleaner -- but certainly not so far as squashing them all. Look forward to hearing from you!

What branch protection rule would you like me to add re: the 3.x support branch?

**Comment by marksweb** [comment]
@chrisclark Ok, that makes sense. So a "sometimes squash" approach might be best because that's certainly valid.

But on the whole, once commits have been through the review of a PR you iron out anything that might need that more granular context. At that point, a single commit for the change gives you what you need. You could also go and look at the individual commits from a PR.

For example, you can see each commit here; https://github.com/django-cms/django-cms/pull/7744/commits

But that merged as a single commit, which for me at least, makes it easier to see the changes going on as it groups the changes in the main branch. (Though I still appreciate your reasoning for a regular merge commit)

I've also spent too many years working with developers who right terrible commit messages, or don't change their commit messages between commits so there's multiple "changed stuff" messages. You can get rid of those with a squashed commit. Again, not an issue where you're doing to be commiting/merging.

As far as branch protection goes, it just needs whatever master has as it should be treated the same.
